DEBUG    		= True
UPLOAD_TO		= './tmp'
DATABASE 		= './living_in_the_.db'
MAX_SIZE_MB		= 50
ALLOWED_AUDIO 	= ['flac', 'mp3', 'ogg']
ALLOWED_IMAGE 	= ['jpg', 'jpeg', 'png']
ALLOWED_FILE	= ['pdf']
ALLOWED_TEXT	= ['css', 'conf', 'htm', 'html', 'js', 'py', 'sh', 'txt']
ALLOWED_VIDEO	= ['mp4', 'webm']
